const common = {
  range: 180,
  standingAccuracy: 0.001,
  crouchingAccuracy: 0.0006,
  movementAccuracy: 0.029,
  airAccuracy: 0.055,
  landingAccuracy: 0.015,
  recoveryDelay: 0.24,
  recoveryRate: 7,
  maxRecoil: 0.024,
  recoilPerShot: 0.002,
  kick: 0.065,
  cameraKick: 0.006,
  horizontalKick: 0.0025,
  speedMultiplier: 1,
  drawTime: 0.28,
  falloff: 0.003,
  sound: "shot",
};
export const WEAPONS = Object.freeze({
  ar4: Object.freeze({
    ...common,
    id: "ar4",
    viewmodel: Object.freeze({
      positionX: 0.255,
      positionY: -0.255,
      positionZ: -0.7,
      rotationX: 0,
      rotationY: -0.045,
      rotationZ: 0.01,
      scale: 1,
    }),
    name: "AR-4",
    type: "5.56 / AUTOMATIC",
    damage: 34,
    interval: 0.105,
    magazine: 30,
    reserve: 90,
    reloadTime: 2.15,
    automatic: true,
    price: 2650,
    description: "Versatile automatic rifle. Control recoil with short bursts.",
  }),
  r45: Object.freeze({
    ...common,
    id: "r45",
    viewmodel: Object.freeze({
      positionX: 0.235,
      positionY: -0.23,
      positionZ: -0.54,
      rotationX: 0,
      rotationY: -0.04,
      rotationZ: 0,
      scale: 1.05,
    }),
    name: "R45",
    type: ".45 / HEAVY PISTOL",
    damage: 59,
    interval: 0.32,
    magazine: 7,
    reserve: 35,
    reloadTime: 2.4,
    automatic: false,
    price: 780,
    standingAccuracy: 0.0007,
    crouchingAccuracy: 0.0004,
    recoveryDelay: 0.36,
    recoveryRate: 4.2,
    maxRecoil: 0.1,
    recoilPerShot: 0.027,
    kick: 0.105,
    cameraKick: 0.041,
    horizontalKick: 0.007,
    speedMultiplier: 1.03,
    sound: "heavyPistol",
    description: "Seven decisive shots. Let the recoil settle between taps.",
  }),
  titan: Object.freeze({
    ...common,
    id: "titan",
    viewmodel: Object.freeze({
      positionX: 0.27,
      positionY: -0.27,
      positionZ: -0.86,
      rotationX: 0,
      rotationY: -0.04,
      rotationZ: 0,
      scale: 1,
    }),
    name: "TITAN",
    type: "12.4 / BOLT ACTION",
    damage: 142,
    interval: 1.55,
    boltTime: 1.55,
    magazine: 5,
    reserve: 20,
    reloadTime: 3.6,
    automatic: false,
    price: 5100,
    scopeFovs: Object.freeze([35, 17]),
    hipAccuracy: 0.095,
    standingAccuracy: 0.00025,
    crouchingAccuracy: 0.00015,
    movementAccuracy: 0.075,
    airAccuracy: 0.14,
    landingAccuracy: 0.06,
    recoveryRate: 5,
    kick: 0.135,
    cameraKick: 0.035,
    horizontalKick: 0.002,
    recoilPerShot: 0.009,
    speedMultiplier: 0.72,
    drawTime: 0.55,
    falloff: 0.001,
    sound: "sniper",
    description:
      "Heavy, precise, unforgiving. Scope, stop, fire, cycle the bolt.",
  }),
});
